<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="..\AuthService\Protos\auth.proto" GrpcServices="Client" />
    <Protobuf Include="..\PoliceService\Protos\police.proto" GrpcServices="Client" />
    <Protobuf Include="..\FireService\Protos\fire.proto" GrpcServices="Client" />
    <Protobuf Include="..\MedicalService\Protos\medical.proto" GrpcServices="Client" />
    <Protobuf Include="..\EmergencyService\Protos\emergency.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.15" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth.Blacklist\Auth.Blacklist.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
