apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-service
  namespace: emergency-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-service
  template:
    metadata:
      labels:
        app: medical-service
    spec:
      containers:
      - name: medical-service
        image: ghcr.io/urangegaj/emergency-hub/medical-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: ConnectionStrings__MedicalDb
          value: "Host=postgres;Port=5432;Database=medical_db;Username=postgres;Password=postgres"
        ports:
        - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: medical-service
  namespace: emergency-hub
spec:
  selector:
    app: medical-service
  ports:
  - port: 5006
    targetPort: 5006
