// <auto-generated />
using System;
using EmergencyService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyService.Data.Migrations
{
    [DbContext(typeof(EmergencyDbContext))]
    [Migration("20260521222126_AddEmergenciesReplicaIdentity")]
    partial class AddEmergenciesReplicaIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyService.Models.Emergency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmergencyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyTypeId");

                    b.HasIndex("CityId", "Status");

                    b.ToTable("Emergencies");
                });

            modelBuilder.Entity("EmergencyService.Models.EmergencyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmergencyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyId", "DepartmentType")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EmergencyService.Models.EmergencyStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmergencyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("EmergencyService.Models.EmergencyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmergencyTypes");
                });

            modelBuilder.Entity("EmergencyService.Models.Emergency", b =>
                {
                    b.HasOne("EmergencyService.Models.EmergencyType", "EmergencyType")
                        .WithMany()
                        .HasForeignKey("EmergencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyType");
                });

            modelBuilder.Entity("EmergencyService.Models.EmergencyAssignment", b =>
                {
                    b.HasOne("EmergencyService.Models.Emergency", "Emergency")
                        .WithMany("Assignments")
                        .HasForeignKey("EmergencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emergency");
                });

            modelBuilder.Entity("EmergencyService.Models.EmergencyStatusHistory", b =>
                {
                    b.HasOne("EmergencyService.Models.Emergency", "Emergency")
                        .WithMany("StatusHistory")
                        .HasForeignKey("EmergencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emergency");
                });

            modelBuilder.Entity("EmergencyService.Models.Emergency", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
